apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIwNDUxMDQ1MjQ1ODUuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdz
LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsTE1uaE5ZbTVD
Tms1WGVIVldhMUkxVVc1Wk1tUlZXalZPUjNoeFdsVTFUVXd3ZUhGaFIyaFlaRzFrYWsxWFRtaE5N
VTVwVmtoc1JVMUVTVFJsUld4RFUwWk9SVTR4WjNoamJsVjJWVVZrYlU1RmVIRmliRTVoWlZWd1Qy
VnNWbGxVTVVZd1dtNWtOazlWTVZsTlJVbzFURE5TV21GSWJETmxibXMxVG01Q1IxTkZWWEpTVjI5
M1VURmFkbU41T1V4UFJVcHpWMjVzY1ZOVlVrWlhXR3hhVXpCc2MySXdjRmRUVkVZMVZqTm9VbHBy
Um5WV1IzQk1ZVmhOTldSdWJ6QmtNa1pZVFd0V2FFOVZNVE5rTVZKUVlVUlZOVll5VWpOTE1FcDFV
VzVvYUdSV1duUk9lbEowWkZWR1VXSXhhR0ZOYkhCMVduazVTVmxUT1d0VlYxcFNUMGRqTkZwRlJt
NU9iR2hIWWxkNE1sRlVUa1ZWYkdoSlZFUkZOVk51UlhsU1ZVcFBZek5XU2xwcVl6UmlTR1J3WTJ0
b1VGUXpUak5SYWtFMVUxVmFZV05WVVRKTlIzaDJaRlZTTW1ReGJFUlpiR1JWVERGb2JGTllRbFpO
UmtwTFQxUmtZV1F6UmtWTk1HeFJZMjFzVVZsWVRUVmFWVGt3VGxWVk1GbFhiM2xOYXpsS1Vtc3hS
MDVZVlRWVWVtc3lVMVZzUjA0emFHRldiVlYzVG10b1Jrd3liM3BrUlc5NFpVaG9iMWRVYUU1amFY
UlJaR3BzVTFkWFVscFdiRkpPVFZWd05Fd3dTWHBaTTJSM1lucGtWazR5VWxkVGExWkxXVEJ3VkZS
RVFYcFNTRll6V2taa1dVNXRkRmxhUm14MlZXeFdiVkpyZUhsT1JUVmhUa1JvYVZsdWJIbFdWMVUw
VWxaU1RsSkVUbWxpVjBwR1pHeFNhMk5WZURSTE1XaHFZbTFOTTAxWWJFMU5WMFUxWkVoYWFHSlhV
alJoYms1UldrUkplVk5zUm5SYVJYaElWVEIwUzJOSWFHOWhWV2hQWTIxU2RsWklSbEpoVmtVeVky
cE9hMU42WkhOa1NFcHhZekp3ZDFaWVVubFJWMVpPWkZkT2RGUnRSWEpQU0ZsNVkwTjBNbGRxUmpa
aVIyeERZVzF3Y2xORlNuaFBSbEpaWTJ0NFZWTnNWblJQVXpsdFZtdHNWVlZUT0hKbFIzUjJVa04w
VW1Kc1JubGtSRUpGWTBWa1ZXVlhSbmxMZWtwV1YyMUdiRlZFYXpCVGJVNVVaRzVDVVZGck1WQlpW
VTVXVWxkSmRtSnRUblZVZWxwNllrWlNXV1I2UW5SV1YzUXpUMGQ0UTJNd1JrbFhXRmw2VTFWb1ZW
bHRPSGRWVjFKV1ZETk5lRTF0ZEROTU1tOTVaRVZzVW1ReWVGaGlhMmd3V2xSS2VGWXdPVVpoTVVF
elV6RmtNVmRzV2xWYVZrVjJWVlpvUldWdE1IbGtWbWg1WldzeFNWTlhPVFJsVlZwQ1lsTjBlR1ZJ
U25ObFZrWlhWRWM1UWxveFRUSmliR3hFVFcxT1dWZFZjSE5YUkVKNFpESXhUbUpVU2xGV1ZFcDRa
RlZLYkdSR1NUQlhiWGgzWTJwU1ZWSllRbkZUYWxKSVVUSndZVmREY3pOT2JFSmhWVEJTVTFKWFRY
cFBWMlJhVm1rNVJXUkVZekZsUmxwNlRYcG9TbHBFU2paWmJrazFaRlZhUm1ScGRGbFdhWE40VjJw
VmVXRXhRbUZrTW5CMVdUSmtkbUl5VWpaaGVrNXJUbFJhTVZGc2NGWlRWRUp5VFc1S1dsSnJVbmhW
ZWs1YVN6Tm9iR05WVG5KaE1VNVZWR3hDUkZGVVl6RlJNVW8wWlVod1ZFNXFSblZUVm14TldXdFdi
RTFwT1hkVmJtaEVUakJ3ZGxwRVVuUlNWR3haWkd4S01GWkVVbGhrTVZwM1pHdEthVlJGVG5GVGVt
aE9VMWhHUkU5V1JuTmhWMnhPVkZaak1WUlZlRFpVUlhSVlpFVTFlVnBxYkcxTE1GWk1WVVprYmxO
cmJESmhSVVV5VXpKV1lXTnJaRkphVXpselkwWmpkbUZ1VW5aYVJ6RjNUbFpOZUZsdVdrTldlVGxx
VWtkMFFtTkZiRTFqVkVaSVpGaFpkMU5xUW0xWlZVcDZZMGhhZEZKR1RteFpNMmcyVlZaT05sZEla
RTVrUlZaNFlWaG9hR0l3ZEdsamFsWnJaRlJvTUZacmJGRlhSR1J2WTFoV1ExSlhTak5OV0VaSVVt
NU9kVTB6UWtwWFZWSlJVVzEwVGxwRlZUSmtlbVJHWkZad2FVOURPWEZOZWxaT1kxZGtTbGRYVFhs
amJHdDJWMVJLYkdNelNsbGlhM1JJVERKSmRsZHJaSFpQUjJNeVQwY3hTbHBGUm5wU1YzQlFWMWRH
VVZscE9WQmhNMDEyV2tSa2JrMXBPRE5hTWpRMVQwVmtUMU5IYjNkT1JUUXpWR3hGTUZOSWFGVmhN
alZVVGpCc2VGWkhUWHBoUjA1SFpGaEtlbUZyT1hWVk1YQkNUbTF6TUdFeGJGUlphWFIzVERJeE1X
VlZkRWhMTWtWNVlqSm9jbFF5YUZwTU1rNXhXV3BHUzFremNFOWthMmhxWXpKV2JWZEdjRmhWYmxr
d1VsVk9jVlZ1UlROVVZrcElXVEJPYm1Sc1ZtdGFhMlJEVkZSR2VGTnRVbkJpVXpsdVRqTktTRk5W
WkRWTlZUbDJVMFJvV2xack5YRlRSbFV5V1c1d1JtRlhjM1pOYXpWMFZtMVpkMk51Vm5wVGEwWjVa
RVJTYUZrelZYZFdTRUYzVkhsemVVNVlZelZhUjA1clpGVXdNbG94V1hsTldHaDJZMFpvVVZvd2RF
WlNWM2hWWWxoT1VXTldaR2hsYW1SNVlVUmFVVkpYZUdwT1NFSXhWakE0ZDFWRldYWmhNRTV3VFVS
V1ZFd3haRXBTYVhOMlUwWlplbU42VWtaUlUzUkNaR3hLTWxGWFRqSmhNMDUxU3pGS1Vrc3ljRVZs
YWtKWVlrUkdWbUpWVm5CV2JsWTJZV3hrY1ZKRk9IbFVNMHByVjBoU1NsZElXa3hqZWxwT1RXMW9k
azB3YUhOUFZXaHRWWHBzY1ZkVVNrcGpNRXAzUzNwb1VscEVRa05SYXpWVVZqSnZNbEV4VW5sV2JG
WllUVmRPTlZOR2NFSlpiV2hZWWxSQ1YxUlhNSHBOVnpWdlQwZFplRkV5VG0xWFIzaFpUSHBLVFU1
SFpFcGtSazU2V1RJMWVVMHpXbkJTVjBwU1kwUktRMUZXWjNKaFYwWktVMWRzTTFOdGMzbFhVemxv
V1d4Uk0xcEZVa3hrVjNoWFdrZFNhVlZZUmpKaU0xcHBWVzFrZEdSclJtbGFlbFpMVFZacmVWSkhO
VmhXVnpGUVl6RkJlbUZVUWt0VldGRjJWREJXV1U1VE9YcFBWWFJQVFd0S1VsSklaRkZrYWtaRVZU
QmFUbU5IVm5WTlYyOHdZMVprVGxGclJuRmlTRXBwVjFab1NWSlZiRXBTYWs1TllWZGtWRTVyV2pO
a1J6RlpUa1JPVGsweVpEWmxXRVl4VGtoTk5VOUVZM2RQU0ZreVUxWkNkbE5FVmxOUmEzQkRWREJT
YVdKV1drcGxSVFZ2VjFWV2RsbHBkSFZTTTNCQ1VsVkdRMVJITVd0ak1uTXpTek5zY0U5R1RtaGlN
VnBvVjIxYVVHTkhUVFJUYTJ0NllrZFNXR051V25KUFJrWnZaRlUwZDJRd2RFSlFWREJwVEVOS2Ex
bFlVbWhoTWxZMVNXcHZhVkZXUmtaUmEwWkpZVWhrZEUxR2JHaFRWazVMV2xaS01GTnRNREZpYWta
SVRtNVdlRnBYVm5KWFNGWjJWMFpvVVZwVVZsWlNiVTVzVDFaS2VFOURPSGhPU0dSQ1VWVkdTVTVJ
WkcxUlZteExVekk1WVZOWGFESlpNRFZDVlZkT1NHSXdZelJrTWtwU1UxVktRbEpGU25aUmJXUnlZ
MWRvY21GVll6Vmtla0pEVVc1a1JtUXdhRzVYVlhCYVUxWndTbEZXWkZaU1JVcENVbGhXVGxGclZr
WlNSWFJIVDFSU2NWRXhWa1ZPVkZaVFRURk9OR013T1ZKVFZVcEdVMVZGTTFKVldrdE1NMFpUVkVW
ak1WTkhOVzVQV0VwaFRtNWFTVlJzYkhkUFZGcFVUa1ZqZG1ONlNqVmxWbkJ6UzNwck5WSXhUWFpX
Ym5CaFVsZFNNR0Z1UmpKaVJrNXRWV3RPVDAxcVFrWmFia295VFdwbk0wd3lOSGhPV0ZsM1lYbHpj
bGxZVlhkaGEwMDBZM293YVV4RFNqSmFXRXA2WVZjNWRVbHFiMmxOYVVselNXNVNOV05IVldsUGFV
cEZVVlpTUWxnd2RFWlhVMGx6U1cxV05HTkhiSGxaV0ZKd1lqSTBhVTlxUlROTlZFa3hUbFJyTWs1
RVRqaz0iCgkJfQoJfQp9