kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-test-pvc
  namespace: final
  labels:
    app.kubernetes.io/name: app-test
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: employeeapp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
